/**
 * RAIN V6 — QC (Quality Control) logic — single source of truth for the
 * 18-point QC check definitions used by the analytics pipeline.
 *
 * Used by:
 *   - QCTab.tsx — live QC display (the tab re-implements the same checks
 *     inline because it ALSO needs the async Ed25519 verify + Chromaprint
 *     re-compute results, which are not available synchronously here)
 *   - MasteringTab.tsx — persists a per-render QC snapshot to IndexedDB via
 *     recordQCResult() so the Analytics tab can compute pass/fail rates and
 *     common failure categories across the render history.
 *
 * Every check is computed from REAL analysis fields (LUFS, true-peak, LRA,
 * crest factor, phase correlation, DC offset, etc.) — no fabricated
 * verdicts, no Math.random, no constant PASS results.
 *
 * NOTE on the two provenance checks: in this synchronous analytics path
 * the cert was JUST generated by generateProvenance() seconds ago, so by
 * construction the Ed25519 signature is valid and the Chromaprint hash is
 * embedded. We check cert presence + hash presence here. The live QCTab
 * re-verifies the signature and re-computes the fingerprint asynchronously
 * for an independent second opinion.
 */

import type { AudioAnalysis, ProvenanceCertificate, PlatformTarget } from './types'
import type { QCStatus } from './analytics'

export interface QCCheckResult {
  id: string
  name: string
  category: 'loudness' | 'dynamic' | 'spectral' | 'stereo' | 'format' | 'provenance' | 'transient'
  status: QCStatus
  measured: string
  target: string
  message: string
}

type CheckStatus = 'pass' | 'warn' | 'fail'

/**
 * Compute the 18-point QC verdict for the given analysis + cert + platform.
 * Returns an empty "awaiting render" placeholder when no analysis is present
 * (matches the prior QCTab behaviour so the live tab still shows a hint).
 *
 * Every measured value is derived from `analysis` (the real AudioAnalysis
 * produced by analyzeAudio) or from `cert` (the just-generated
 * ProvenanceCertificate). No constants.
 */
export function computeQCResults(
  analysis: AudioAnalysis | null,
  platform: PlatformTarget,
  cert: ProvenanceCertificate | null,
): QCCheckResult[] {
  if (!analysis) {
    return [
      {
        id: 'qc_no_data',
        name: 'Awaiting render',
        category: 'loudness',
        status: 'warn',
        measured: '—',
        target: '—',
        message: 'Run the 16-stage pipeline to populate QC checks.',
      },
    ]
  }
  const q = analysis.qcMetrics
  const targetLufs = platform.targetLufs
  const truePeakCeiling = platform.truePeakCeiling
  const lufsDelta = Math.abs(analysis.lufs - targetLufs)
  const tpExcess = analysis.truePeak - truePeakCeiling

  // ---- per-check status (each derived from a real measurement) ----
  const lufsStatus: CheckStatus = lufsDelta < 1 ? 'pass' : lufsDelta < 3 ? 'warn' : 'fail'
  const tpStatus: CheckStatus = tpExcess <= 0 ? 'pass' : tpExcess <= 0.5 ? 'warn' : 'fail'
  const lraStatus: CheckStatus = analysis.dynamicRange >= 5 && analysis.dynamicRange <= 9
    ? 'pass'
    : analysis.dynamicRange < 3 || analysis.dynamicRange > 12 ? 'fail' : 'warn'
  const crestStatus: CheckStatus = analysis.crestFactor >= 6 ? 'pass' : analysis.crestFactor >= 4 ? 'warn' : 'fail'
  const rmsStatus: CheckStatus = q.rmsDb >= -22 && q.rmsDb <= -10
    ? 'pass'
    : q.rmsDb < -30 || q.rmsDb > -6 ? 'fail' : 'warn'
  const widthStatus: CheckStatus = q.stereoWidth >= 0.8 && q.stereoWidth <= 1.3
    ? 'pass'
    : q.stereoWidth < 0.5 || q.stereoWidth > 1.6 ? 'fail' : 'warn'
  const corrStatus: CheckStatus = q.phaseCorrelation > 0.5 ? 'pass' : q.phaseCorrelation > 0.0 ? 'warn' : 'fail'
  const dcStatus: CheckStatus = q.dcOffset < 0.001 ? 'pass' : q.dcOffset < 0.005 ? 'warn' : 'fail'
  const phaseStatus: CheckStatus = q.phaseCoherence > 0.9 ? 'pass' : q.phaseCoherence > 0.5 ? 'warn' : 'fail'
  const bassStatus: CheckStatus = q.bassSideDb < -18 ? 'pass' : q.bassSideDb < -12 ? 'warn' : 'fail'
  const rumbleStatus: CheckStatus = q.rumbleDb < -60 ? 'pass' : q.rumbleDb < -45 ? 'warn' : 'fail'
  const sibStatus: CheckStatus = q.sibilanceDb < -10 ? 'pass' : q.sibilanceDb < -5 ? 'warn' : 'fail'
  const hfStatus: CheckStatus = q.highFreqDb > -45 ? 'pass' : q.highFreqDb > -60 ? 'warn' : 'fail'
  // Bandwidth Integrity — detects a clean high-frequency cutoff (the
  // "16-18 kHz cliff" produced by MP3/AAC encoders or lossy sources).
  // effectiveBandwidthHz is the highest bin within 40 dB of the spectral
  // peak; for a 48 kHz master it should be ≥ 21 kHz. 16-18 kHz = FAIL.
  const bwKHz = q.effectiveBandwidthHz / 1000
  const nyquistKHz = analysis.sampleRate / 2000
  const bwStatus: CheckStatus = bwKHz >= nyquistKHz * 0.92
    ? 'pass'
    : bwKHz >= 18
      ? 'warn'
      : 'fail'
  const zcStatus: CheckStatus = q.zeroCrossingStuck === 0 ? 'pass' : q.zeroCrossingStuck < 10 ? 'warn' : 'fail'
  const clipStatus: CheckStatus = q.clippedSamples === 0 ? 'pass' : q.clippedSamples < 10 ? 'warn' : 'fail'
  const codecStatus: CheckStatus = q.preechoRisk < 0.3 ? 'pass' : q.preechoRisk < 0.6 ? 'warn' : 'fail'

  // Provenance + fingerprint: for the analytics snapshot, the cert was
  // JUST generated — the Ed25519 signature is valid by construction and
  // the Chromaprint hash is embedded if computeFingerprint succeeded.
  // The live QCTab does the real async re-verification; here we check
  // structural presence only.
  const fingerprintHash = cert?.manifest.assertions.find(
    (a) => a.label === 'org.rain.fingerprint',
  )?.data as { hash?: string | null } | undefined
  const provStatus: CheckStatus = cert ? 'pass' : 'warn'
  const fpStatus: CheckStatus = fingerprintHash?.hash ? 'pass' : cert ? 'warn' : 'warn'

  return [
    {
      id: 'qc_lufs',
      name: 'LUFS (BS.1770-4)',
      category: 'loudness',
      status: lufsStatus,
      measured: `${analysis.lufs.toFixed(1)} LUFS`,
      target: `${targetLufs} ±1 LU`,
      message: lufsDelta < 1 ? 'Within target' : `${(analysis.lufs - targetLufs).toFixed(1)} LU from target`,
    },
    {
      id: 'qc_true_peak',
      name: 'True Peak (4× OS)',
      category: 'loudness',
      status: tpStatus,
      measured: `${analysis.truePeak.toFixed(2)} dBTP`,
      target: `≤ ${truePeakCeiling} dBTP`,
      message: tpExcess <= 0 ? 'Within ceiling' : `${tpExcess.toFixed(2)} dB over ceiling`,
    },
    {
      id: 'qc_lra',
      name: 'Loudness Range (LRA)',
      category: 'dynamic',
      status: lraStatus,
      measured: `${analysis.dynamicRange.toFixed(1)} LU`,
      target: '5–9 LU',
      message: analysis.dynamicRange >= 5 && analysis.dynamicRange <= 9 ? 'Ideal range' : 'Outside sweet spot',
    },
    {
      id: 'qc_crest_factor',
      name: 'Crest Factor',
      category: 'dynamic',
      status: crestStatus,
      measured: `${analysis.crestFactor.toFixed(1)} dB`,
      target: '≥ 6 dB',
      message: analysis.crestFactor >= 6 ? 'Healthy transient retention' : 'Heavy compression',
    },
    {
      id: 'qc_rms',
      name: 'RMS Level',
      category: 'loudness',
      status: rmsStatus,
      measured: `${q.rmsDb.toFixed(1)} dBFS`,
      target: '−22 – −10 dBFS',
      message: q.rmsDb >= -22 && q.rmsDb <= -10 ? 'Healthy RMS level' : q.rmsDb < -22 ? 'Quiet — may need gain' : 'Hot — risk of clipping',
    },
    {
      id: 'qc_stereo_width',
      name: 'Stereo Width (M/S)',
      category: 'stereo',
      status: widthStatus,
      measured: q.stereoWidth.toFixed(2),
      target: '0.8 – 1.3',
      message: q.stereoWidth >= 0.8 && q.stereoWidth <= 1.3 ? 'Balanced stereo image' : q.stereoWidth > 1.3 ? 'Wide — mono-compat risk' : 'Narrow',
    },
    {
      id: 'qc_stereo_correlation',
      name: 'Stereo Correlation',
      category: 'stereo',
      status: corrStatus,
      measured: q.phaseCorrelation.toFixed(2),
      target: '> 0.5',
      message: q.phaseCorrelation > 0.5 ? 'L/R correlated' : q.phaseCorrelation < 0 ? 'Out of phase — mono collapse' : 'Weak correlation',
    },
    {
      id: 'qc_dc_offset',
      name: 'DC Offset',
      category: 'spectral',
      status: dcStatus,
      measured: `${(q.dcOffset * 100).toFixed(3)}%`,
      target: '< 0.1%',
      message: q.dcOffset < 0.001 ? 'Negligible DC offset' : 'DC offset present',
    },
    {
      id: 'qc_phase',
      name: 'Phase Coherence',
      category: 'stereo',
      status: phaseStatus,
      measured: q.phaseCoherence.toFixed(2),
      target: '> 0.9',
      message: q.phaseCoherence > 0.9 ? 'Strong phase coherence' : q.phaseCoherence < 0 ? 'Phase issues (out of phase)' : 'Reduced coherence',
    },
    {
      id: 'qc_bass_mono',
      name: 'Bass Mono (≤ 200 Hz)',
      category: 'stereo',
      status: bassStatus,
      measured: `${q.bassSideDb.toFixed(1)} dB side`,
      target: 'side < −18 dB',
      message: q.bassSideDb < -18 ? 'Bass frequencies mono-compatible' : 'Excess bass in side channel',
    },
    {
      id: 'qc_rumble',
      name: 'Subsonic Rumble',
      category: 'spectral',
      status: rumbleStatus,
      measured: `${q.rumbleDb.toFixed(1)} dB < 20 Hz`,
      target: '< −60 dB',
      message: q.rumbleDb < -60 ? 'Subsonic content filtered' : 'Subsonic energy present',
    },
    {
      id: 'qc_sibilance',
      name: 'Sibilance (5–8 kHz)',
      category: 'spectral',
      status: sibStatus,
      measured: `${q.sibilanceDb.toFixed(1)} dB @ 5–8 kHz`,
      target: '< −10 dB',
      message: q.sibilanceDb < -10 ? 'Sibilance under control' : 'Sibilance may be hot',
    },
    {
      id: 'qc_high_freq',
      name: 'HF Balance (15+ kHz)',
      category: 'spectral',
      status: hfStatus,
      measured: `${q.highFreqDb.toFixed(1)} dB @ 15+ kHz`,
      target: '> −45 dB air',
      message: q.highFreqDb > -45 ? 'High-frequency air preserved' : 'Reduced HF air',
    },
    {
      id: 'qc_bandwidth',
      name: 'Bandwidth Integrity',
      category: 'spectral',
      status: bwStatus,
      measured: `${bwKHz.toFixed(1)} kHz / ${nyquistKHz.toFixed(1)} kHz Nyquist`,
      target: `≥ ${(nyquistKHz * 0.92).toFixed(1)} kHz`,
      message: bwKHz >= nyquistKHz * 0.92
        ? `Full bandwidth — no encoder lowpass detected`
        : bwKHz >= 18
          ? `Mild HF roll-off — ${bwKHz.toFixed(1)} kHz (possible lossy source)`
          : `Clean cutoff at ${bwKHz.toFixed(1)} kHz — lossy lowpass detected (MP3/AAC source or encoder filter)`,
    },
    {
      id: 'qc_zero_crossings',
      name: 'Zero-Crossing Analysis',
      category: 'spectral',
      status: zcStatus,
      measured: `${q.zeroCrossingRate.toFixed(0)} zc/s · ${q.zeroCrossingStuck} stuck`,
      target: 'no stuck-at-zero',
      message: q.zeroCrossingStuck === 0
        ? `${q.zeroCrossingRate.toFixed(0)} crossings/sec, no stuck-at-zero`
        : `${q.zeroCrossingStuck} samples stuck at zero near full-scale`,
    },
    {
      id: 'qc_clipping',
      name: 'Clipping Detection',
      category: 'dynamic',
      status: clipStatus,
      measured: `${q.clippedSamples} samples ≥ ±0.99`,
      target: '0 samples',
      message: q.clippedSamples === 0 ? 'No digital clipping' : `${q.clippedSamples} samples at full-scale`,
    },
    {
      id: 'qc_codec_prediction',
      name: 'Codec Pre-Echo Risk',
      category: 'transient',
      status: codecStatus,
      measured: `risk ${q.preechoRisk.toFixed(2)} · ${q.transientDensity.toFixed(1)} onsets/s`,
      target: '< 0.3 risk',
      message: q.preechoRisk < 0.3
        ? 'Low pre-echo risk at typical lossy bitrates'
        : q.preechoRisk < 0.6
          ? 'Moderate pre-echo risk — transients + level'
          : 'High pre-echo risk — lossy codecs may smear',
    },
    {
      id: 'qc_provenance',
      name: 'Provenance Validation',
      category: 'provenance',
      status: provStatus,
      measured: cert ? 'Ed25519 signed' : 'Pending',
      target: 'signature valid',
      message: cert ? `Cert ${cert.certId.slice(0, 24)}` : 'Certificate not yet generated',
    },
    {
      id: 'qc_fingerprint',
      name: 'Fingerprint Verification',
      category: 'provenance',
      status: fpStatus,
      measured: fingerprintHash?.hash ? `${fingerprintHash.hash.slice(0, 12)}…` : 'Type only',
      target: 'hash embedded',
      message: fingerprintHash?.hash ? 'Chromaprint hash embedded in cert manifest' : 'No fingerprint hash available',
    },
  ]
}

/**
 * Reduce a list of QC check results into the persisted QCRecord body (no id —
 * recordQCResult assigns one). Used by MasteringTab after each render to
 * persist a QC snapshot for the Analytics tab.
 */
export function summarizeQCResults(
  checks: QCCheckResult[],
  platform: string,
  renderId: string | null,
  timestamp: number,
): Omit<import('./analytics').QCRecord, 'id'> {
  let passCount = 0
  let warnCount = 0
  let failCount = 0
  const categories: Record<string, { pass: number; warn: number; fail: number }> = {}
  const compactChecks = checks.map((c) => {
    if (c.status === 'pass') passCount += 1
    else if (c.status === 'warn') warnCount += 1
    else failCount += 1
    const acc = categories[c.category] ?? { pass: 0, warn: 0, fail: 0 }
    acc[c.status] += 1
    categories[c.category] = acc
    return { id: c.id, status: c.status }
  })
  return {
    timestamp,
    renderId,
    platform,
    passCount,
    warnCount,
    failCount,
    categories,
    checks: compactChecks,
  }
}
